frameworkVersion: '2'
service: authorization-service

plugins:
  - serverless-bundle
  - serverless-dotenv-plugin
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  # region: eu-west-1
  region: us-east-1
  lambdaHashingVersion: 20201221

functions:
  basicAuthorizer:
    handler: src/handlers/handlers.basicAuthorizer

resources:
  Resources:
  Outputs:
    basicAuthorizerArn:
      Value:
        Fn::GetAtt:
          - BasicAuthorizerLambdaFunction
          - Arn
